name: build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get version
        id: version
        run: echo "VERSION=$(cd tunasync && git fetch && git describe --tags | sed 's/^v//')" >> $GITHUB_OUTPUT

      - name: Build
        uses: ngc7331/actions@docker-build
        with:
          name: tunasync
          version: ${{ steps.version.outputs.VERSION }}
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/riscv64
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
